name: "telegram"
version: "0.0.8"
description: "Telegram Bot API wrapper for Dart"
author: "Sungjin Han <meinside@gmail.com>"

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  crypto: "^2.0.6"
  uuid: "^1.0.1"
  http: "^0.11.3"
  json_serializable: "^1.0.0"
  json_annotation: "^1.0.0"
  intl: "^0.15.7"

dev_dependencies:
  build_runner: "^0.10.0"

publish_to: "none"
