name: "telegram"
version: "0.0.1"
description: "Telegram Bot API wrapper for Dart"
author: "Sungjin Han <meinside@gmail.com>"
dependencies:
  crypto: "^2.0.6"
  uuid: "^1.0.1"
  http: "^0.11.3+17"
  json_serializable: "^0.5.8"
  json_annotation: "^0.2.9"
  intl: "^0.15.7"
dev_dependencies:
  build_runner: "^0.9.0"
  json_serializable: "^0.5.8"
sdk: '>=2.0.0-dev.54 <3.0.0'
publish_to: "none"
